# Generated by Django 4.1.5 on 2023-02-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
